name: Auto Update Stock Prices

on:
  workflow_dispatch: # Manual run option
  schedule:
    # From 9:00 AM IST (03:30 UTC) to 11:30 PM IST (18:00 UTC) every 30 min
    - cron: "30 3-17/1 * * *" # 9:00 AM, 10:00 AM, 11:00 AM IST, etc.
    - cron: "0 4-18/1 * * *"  # 9:30 AM, 10:30 AM, 11:30 AM IST, etc.

jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock update script
        run: python update_stock.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update stock prices" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
