name: Auto Update Stock Prices

on:
  workflow_dispatch:  # Allows manual run from GitHub Actions
  schedule:
    
    - cron: "*/5 1-17 * * *"   # Every 5 minutes, 7:00–23:00 IST, all days
    
jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance openpyxl

      - name: Run stock update script
        run: python update_stock.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add SKV_Sheet_1_Updated.csv
          git commit -m "Auto update stock prices" || echo "No changes to commit"
          git push
